<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-M8LBSK5" failures="0" tests="2" name="com.log4j2example.test.Log4j2ExampleTest.TestLoggingLog4j" time="0.007" errors="1" timestamp="2022-05-11T15:57:06 IST" skipped="1">
  <testcase classname="com.log4j2example.test.Log4j2ExampleTest.TestLoggingLog4j" name="testmain" time="0.000">
    <skipped/>
  </testcase> <!-- testmain -->
  <system-out/>
  <testcase classname="com.log4j2example.test.Log4j2ExampleTest.TestLoggingLog4j" name="testinit" time="0.007">
    <error message="Unresolved compilation problems: 
	LoggerContext cannot be resolved to a type
	LoggerContext cannot be resolved to a type
	LogManager cannot be resolved
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
LoggerContext cannot be resolved to a type
LoggerContext cannot be resolved to a type
LogManager cannot be resolved

at com.log4j2example.test.Log4j2ExampleTest.Log4j2Example.init(Log4j2Example.java:13)
at com.log4j2example.test.Log4j2ExampleTest.TestLoggingLog4j.testinit(TestLoggingLog4j.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testinit -->
  <system-out/>
</testsuite> <!-- com.log4j2example.test.Log4j2ExampleTest.TestLoggingLog4j -->
